name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'  # Every Monday at 09:00 Greece time

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npm run test

      - name: Generate Allure report
        run: npm run allure:generate

      - name: Upload Allure results
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report
